theme: jekyll-theme-slate
#load_paths:
#  - _sass
#  - node_modules
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
author: "Serge Aleynikov"
include:
  - README.md
  - ei-in-port-programs.md
  - gen-event-demystified.md
  - non-blocking-tcp-server.md
  - snmp-quick-start.md
